<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Auditing Carbon at the Scale of the Urban System – Shuai Ma</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-bba5ebae505b5c03f3f0d8040a416a6b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4PQ33SR2WK"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-4PQ33SR2WK', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shuai Ma</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../practice.html"> 
<span class="menu-text">Practice</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#context-and-the-planning-problem" id="toc-context-and-the-planning-problem" class="nav-link" data-scroll-target="#context-and-the-planning-problem">1. Context and the Planning Problem</a></li>
  <li><a href="#research-aim-and-questions" id="toc-research-aim-and-questions" class="nav-link" data-scroll-target="#research-aim-and-questions">2. Research Aim and Questions</a></li>
  <li><a href="#data-and-method" id="toc-data-and-method" class="nav-link" data-scroll-target="#data-and-method">3. Data and Method</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">4. Findings</a></li>
  <li><a href="#from-audit-to-indicators-and-action" id="toc-from-audit-to-indicators-and-action" class="nav-link" data-scroll-target="#from-audit-to-indicators-and-action">5. From Audit to Indicators and Action</a></li>
  <li><a href="#significance" id="toc-significance" class="nav-link" data-scroll-target="#significance">6. Significance</a></li>
  <li><a href="#authors-contribution" id="toc-authors-contribution" class="nav-link" data-scroll-target="#authors-contribution">Author’s Contribution</a></li>
  <li><a href="#limitations-and-directions" id="toc-limitations-and-directions" class="nav-link" data-scroll-target="#limitations-and-directions">7. Limitations and Directions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Auditing Carbon at the Scale of the Urban System</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cp-header">
  <div class="cp-tag">Research Brief · Low-Carbon Urban-System Planning · Carbon Accounting · Arup · 2011</div>
  <h1 class="cp-title">Auditing Carbon at the Scale of the Urban System</h1>
  <div class="cp-subtitle">A Spatial Planning Emissions Model for Jiangsu Province, 2005–2030</div>
  <div class="cp-meta">
    <span class="cp-author">Shuai Ma</span>
  </div>
</div>
<p><strong>Keywords:</strong> urban-system planning; carbon audit; IPCC activity-data method; scenario analysis; carbon intensity; decoupling; Jiangsu Province</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Cities and the regional systems that organize them are now the decisive arena for climate mitigation, yet statutory spatial planning in China has lacked a quantitative tool for testing the carbon consequences of planning choices. This brief reports a carbon audit model built for the revision of the Jiangsu Provincial Urban-System Plan. The model adapts the Intergovernmental Panel on Climate Change (IPCC) activity-data method and reorganizes the greenhouse-gas inventory into eight planning-aligned modules covering ecological space, urban buildings, industry, rural construction, transport, water, waste, and alternative energy. Applied across thirteen prefecture-level cities for a 2005 to 2030 horizon under baseline, low-carbon, and policy scenarios, the model shows that coordinated planning policy can hold 2030 provincial emissions to 1,713 million tonnes of carbon dioxide equivalent (Mt CO₂e), roughly a quarter below the baseline, while lowering the carbon intensity of output well beyond the national target. The study demonstrates how macro-level decarbonization goals can be operationalized as measurable indicators inside the statutory planning system.</p>
</section>
<section id="context-and-the-planning-problem" class="level2">
<h2 class="anchored" data-anchor-id="context-and-the-planning-problem">1. Context and the Planning Problem</h2>
<p>Climate change is reshaping the agenda of regional and urban planning. In China, an estimated 85 percent of carbon dioxide emissions originate in cities and towns, which makes the spatial organization of the urban system a primary lever for mitigation. In the run-up to the 2009 Copenhagen conference, the national government pledged to reduce the carbon intensity of gross domestic product (GDP) by 40 to 45 percent from its 2005 level by 2020. Translating that economy-wide pledge into spatial policy, however, requires an analytical bridge between a single national number and the thousands of land-use, infrastructure, and density decisions made through statutory planning.</p>
<p>Provincial urban-system planning (城镇体系规划) is the instrument through which a government coordinates the scale, spatial structure, functional division, and major infrastructure of the cities under its jurisdiction. It therefore governs many of the structural drivers of regional energy and resource use, yet it has traditionally been expressed in qualitative spatial terms rather than in quantities of energy or carbon. Two obstacles followed from this. First, the discipline lacked a measurement tool aligned with how planners actually reason about territory, so the carbon implications of alternative spatial structures could not be compared. Second, most provinces had no consistent, audited emissions baseline or scenario database against which to test policy. This study was commissioned to close both gaps for Jiangsu, one of China’s most populous and economically advanced provinces, with 77.25 million residents and a 2009 GDP of 3.47 trillion yuan distributed across thirteen prefecture-level cities.</p>
</section>
<section id="research-aim-and-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-aim-and-questions">2. Research Aim and Questions</h2>
<p>The study set out to design a carbon audit model that is technically defensible, planner-usable, and embedded in the statutory planning workflow. It pursued three questions. How can a standardized greenhouse-gas inventory be restructured so that its categories correspond to the working modules of spatial planning? How far do alternative planning and policy scenarios change the magnitude, intensity, and spatial distribution of provincial emissions to 2030? And how can the resulting evidence be converted into indicators and actions that planners can write into urban-system, master, and regulatory detailed plans?</p>
</section>
<section id="data-and-method" class="level2">
<h2 class="anchored" data-anchor-id="data-and-method">3. Data and Method</h2>
<p>The model rests on the IPCC accounting identity, in which emissions are estimated as the product of an activity-data term (a measure of how much of a carbon-relevant activity takes place) and an emission factor (the quantity of greenhouse gas released per unit of that activity). The novel step is organizational rather than chemical. Rather than reporting in the IPCC’s standard energy, industrial-process, agriculture, and waste categories, the inventory is recombined into eight modules that mirror the components of an urban-system plan. Figure 1 summarizes the structure of the model, from spatial and administrative inputs through the eight accounting modules and the scenario engine to planning-relevant outputs.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig1_framework.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. Eight-module carbon audit model for urban-system planning</figcaption>
</figure>
</div>
<p>Activity data were assembled for two reference years, a 2009 current-state condition and a 2030 planning horizon, from provincial and municipal statistical yearbooks, construction reports, the urban-system planning documents, national and provincial policies and standards, and projections supplied by the provincial planning institute. Emission and sink-removal factors were drawn from the IPCC national greenhouse-gas inventory guidelines and supporting literature. Each module carries its own sub-model: the ecological-space module, for example, treats paddy fields as a methane source and forest, orchard, grassland, and urban trees as carbon sinks, while the building module combines floor area, climate-zone energy intensity, and fuel-specific factors. Industry, which dominates the provincial total, is estimated from sector value added, energy intensity per unit of value added, and direct process emissions from steel and cement.</p>
<p>Three scenarios convert the static accounts into a forward-looking comparison. The baseline scenario extends current trends and planned construction without additional mitigation. The low-carbon scenario applies energy-efficiency and energy-structure improvements. The policy scenario adds the full set of spatial and regulatory planning instruments available to the province. Results are reported not only as absolute emissions but through two intensity indicators that planners and decision-makers can benchmark, namely carbon emissions per unit of GDP and carbon emissions per capita. Table 1 reports the eight-module accounts for the two reference years.</p>
<p><strong>Table 1. Provincial emissions by accounting module, 2009 and 2030 (baseline)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Accounting module</th>
<th style="text-align: right;">2009 (Mt CO₂e)</th>
<th style="text-align: right;">2009 share</th>
<th style="text-align: right;">2030 (Mt CO₂e)</th>
<th style="text-align: right;">2030 share</th>
<th style="text-align: right;">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Industry</td>
<td style="text-align: right;">611.3</td>
<td style="text-align: right;">74.5%</td>
<td style="text-align: right;">1,788.2</td>
<td style="text-align: right;">72.4%</td>
<td style="text-align: right;">+192%</td>
</tr>
<tr class="even">
<td>Urban buildings</td>
<td style="text-align: right;">89.9</td>
<td style="text-align: right;">11.0%</td>
<td style="text-align: right;">449.4</td>
<td style="text-align: right;">18.2%</td>
<td style="text-align: right;">+400%</td>
</tr>
<tr class="odd">
<td>Transport</td>
<td style="text-align: right;">42.5</td>
<td style="text-align: right;">5.2%</td>
<td style="text-align: right;">126.4</td>
<td style="text-align: right;">5.1%</td>
<td style="text-align: right;">+198%</td>
</tr>
<tr class="even">
<td>Rural construction</td>
<td style="text-align: right;">55.1</td>
<td style="text-align: right;">6.7%</td>
<td style="text-align: right;">68.0</td>
<td style="text-align: right;">2.8%</td>
<td style="text-align: right;">+23%</td>
</tr>
<tr class="odd">
<td>Water</td>
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">0.8%</td>
<td style="text-align: right;">24.9</td>
<td style="text-align: right;">1.0%</td>
<td style="text-align: right;">+288%</td>
</tr>
<tr class="even">
<td>Waste</td>
<td style="text-align: right;">9.8</td>
<td style="text-align: right;">1.2%</td>
<td style="text-align: right;">10.5</td>
<td style="text-align: right;">0.4%</td>
<td style="text-align: right;">+7%</td>
</tr>
<tr class="odd">
<td>Ecological space (net)</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">0.5%</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.02%</td>
<td style="text-align: right;">−87%</td>
</tr>
<tr class="even">
<td>Alternative energy (offset)</td>
<td style="text-align: right;">−19.5</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−202.9</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">+939%</td>
</tr>
<tr class="odd">
<td><strong>Net total</strong></td>
<td style="text-align: right;"><strong>799.3</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
<td style="text-align: right;"><strong>2,264.9</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
<td style="text-align: right;"><strong>+193%</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">4. Findings</h2>
<section id="aggregate-trajectory-and-the-value-of-policy" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-trajectory-and-the-value-of-policy">4.1 Aggregate trajectory and the value of policy</h3>
<p>Under the baseline scenario, net provincial emissions rise from 799 Mt CO₂e in 2009 to 2,265 Mt CO₂e in 2030, an increase of 193 percent and a compound annual growth rate of 4.8 percent. The low-carbon scenario reduces the 2030 total to 1,883 Mt CO₂e, and the policy scenario to 1,713 Mt CO₂e. As Figure 2 shows, the three trajectories are indistinguishable early in the period and diverge after 2015, the point at which planning and efficiency measures begin to bite. The policy scenario avoids roughly 0.55 gigatonnes of CO₂e in 2030 relative to the baseline, a reduction of about 24 percent, and under it the 2030 total is only 114 percent above the 2009 level rather than 193 percent. The baseline curve also continues to climb throughout the horizon and slows only after 2020, which the study reads as a warning that an unmanaged path would place sustained pressure on provincial energy supply.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig2_trajectory.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Province-wide emission trajectories under three planning scenarios, 2005–2030</figcaption>
</figure>
</div>
</section>
<section id="sectoral-structure-and-the-rise-of-buildings" class="level3">
<h3 class="anchored" data-anchor-id="sectoral-structure-and-the-rise-of-buildings">4.2 Sectoral structure and the rise of buildings</h3>
<p>The audit makes the structure of the problem legible. Industry is overwhelmingly dominant, accounting for 74.5 percent of emissions in 2009 and still 72.4 percent in 2030, which means that no provincial decarbonization strategy can succeed without an industrial component. The most important structural shift, however, is the rise of urban buildings, whose share climbs from 11.0 to 18.2 percent as floor area, appliance ownership, and per-square-metre energy use all increase. Transport holds a steady share near 5 percent but grows almost threefold in absolute terms, driven by private cars. Figure 3 displays the module-by-module comparison, including the expanding role of alternative energy, whose avoided emissions grow from 19.5 to 202.9 Mt CO₂e as nuclear, wind, and distributed renewables move from 3 to 13 percent of energy supply.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig3_sectors.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Emissions by accounting module, 2009 versus 2030</figcaption>
</figure>
</div>
</section>
<section id="decoupling-output-from-carbon" class="level3">
<h3 class="anchored" data-anchor-id="decoupling-output-from-carbon">4.3 Decoupling output from carbon</h3>
<p>Because GDP grows faster than emissions, all three scenarios decouple output from carbon. The carbon intensity of provincial GDP falls from 3.22 tonnes CO₂e per ten thousand yuan in 2005 to 1.88 in the 2020 baseline, a 41 percent reduction that only just reaches the lower bound of the national 40 to 45 percent target. The low-carbon and policy scenarios reduce intensity by 47 and 52 percent respectively, comfortably exceeding the pledge, and the policy scenario continues to 1.39 by 2030. Figure 4 places the three scenarios against the national target band and shows clearly that meeting the pledge is feasible under business-as-usual but that surpassing it depends on deliberate planning policy. Table 2 reports the scenario comparison in full.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig4_intensity.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. Carbon intensity of GDP, scenarios versus the national 2020 target</figcaption>
</figure>
</div>
<p><strong>Table 2. Scenario comparison at 2020, relative to 2005</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th style="text-align: right;">Total emissions (Mt CO₂e)</th>
<th style="text-align: right;">Carbon intensity (t / 10⁴ yuan)</th>
<th style="text-align: right;">Intensity vs 2005</th>
<th style="text-align: right;">Per-capita (t / person)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2005 base year</td>
<td style="text-align: right;">574.6</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">7.69</td>
</tr>
<tr class="even">
<td>2020 Baseline</td>
<td style="text-align: right;">1,782.6</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">−41%</td>
<td style="text-align: right;">20.97</td>
</tr>
<tr class="odd">
<td>2020 Low-carbon</td>
<td style="text-align: right;">1,622.4</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">−47%</td>
<td style="text-align: right;">19.09</td>
</tr>
<tr class="even">
<td>2020 Policy</td>
<td style="text-align: right;">1,449.3</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">−52%</td>
<td style="text-align: right;">17.05</td>
</tr>
</tbody>
</table>
</section>
<section id="per-capita-convergence-as-an-equity-signal" class="level3">
<h3 class="anchored" data-anchor-id="per-capita-convergence-as-an-equity-signal">4.4 Per-capita convergence as an equity signal</h3>
<p>The per-capita indicator tells a more cautionary story. Because population grows only modestly while emissions surge, per-capita emissions rise from 7.7 tonnes CO₂e in 2005 to 25.2 tonnes in the 2030 baseline. As Figure 5 illustrates, Jiangsu’s per-capita level in 2009 was comparable to that of the United Kingdom, but on the baseline path it approaches the level of Australia by 2030. This framing reposes the mitigation question as one of development style and consumption, not merely industrial efficiency, and it shows that policy intervention can hold the 2020 per-capita figure to 17.1 rather than 21.0 tonnes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig5_percapita.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. Baseline per-capita emissions converge toward developed-economy levels</figcaption>
</figure>
</div>
<p>The audit also operates at the city scale. Suzhou records the largest absolute emissions in both years, while industrial cities such as Zhenjiang, Wuxi, and Changzhou show industrial shares above 80 percent, and the model links four candidate spatial-structure plans to differences in city-level GDP and emissions growth. The four plans share a common skeleton of one coastal development belt, two urbanization axes, and three metropolitan circles centred on Nanjing, Xuzhou, and the Suzhou–Wuxi–Changzhou corridor, but they differ in how far they extend growth axes into the less developed north of the province. Plans that push development northward raise both GDP and emissions growth in cities such as Xuzhou, Yancheng, and Suqian, which makes the carbon cost of regional rebalancing explicit and quantifiable. This spatial resolution lets planners see which development axes and growth poles carry the heaviest carbon consequences and weigh them against equity goals.</p>
</section>
</section>
<section id="from-audit-to-indicators-and-action" class="level2">
<h2 class="anchored" data-anchor-id="from-audit-to-indicators-and-action">5. From Audit to Indicators and Action</h2>
<p>The audit is a means rather than an end. Its purpose is to support a low-carbon indicator system that can be written into the three tiers of statutory planning, namely the urban-system plan, the master plan, and the regulatory detailed plan. Following the Kaya decomposition, the study treats emissions as the product of development scale, energy efficiency, energy structure, and the emission intensity of each energy source, and on that basis constructs twenty-seven indicators grouped into driver indicators, policy indicators, and effect indicators. Ten of the twenty-seven already exist within current urban-system planning, which eases adoption, while the remainder extend the planning vocabulary toward carbon. Each module is then paired with an action plan keyed to existing provincial policy and the provincial climate-change program, so that an abstract emissions target descends into concrete planning requirements such as land-use composition, building energy codes, public-transport mode share, and renewable-energy deployment.</p>
</section>
<section id="significance" class="level2">
<h2 class="anchored" data-anchor-id="significance">6. Significance</h2>
<p>The contribution of this work is methodological and institutional rather than only empirical. By recombining a standard greenhouse-gas inventory into eight modules that match the working categories of spatial planning, the study makes carbon a quantity that planners can audit, forecast, and regulate using the data and instruments they already possess. It demonstrates a reproducible procedure for moving from a single national intensity pledge to a spatially explicit, multi-scenario, indicator-based plan, and it shows with provincial data that the scenario gap between business-as-usual and active policy is large enough to matter for national targets. The framework is transferable to other provinces facing the same governance gap between climate ambition and statutory spatial planning.</p>
</section>
<section id="authors-contribution" class="level2">
<h2 class="anchored" data-anchor-id="authors-contribution">Author’s Contribution</h2>
<p>As a member of the project team, I contributed to two core components of the study. First, I helped build the multi-sector accounting model that integrates activity data across land use, buildings, industry, transportation, water, waste, and ecological space for the thirteen-city provincial urban system, structuring heterogeneous statistical and spatial inputs into a single consistent framework. Second, I produced the baseline and policy-scenario estimates for 2005 to 2030 using the per-capita and per-GDP intensity indicators reported here, translating spatial and administrative data into planning-relevant quantitative evidence. This work connected the technical accounting layer to the indicator and scenario outputs that planners ultimately use.</p>
</section>
<section id="limitations-and-directions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-directions">7. Limitations and Directions</h2>
<p>The model inherits the uncertainty of its emission factors and of long-horizon activity-data projections, and its 2009 base year predates more recent shifts in China’s energy mix and industrial policy. The strong dependence of the provincial total on a single dominant industrial module also means that results are sensitive to assumptions about industrial restructuring. Future work could update the factors and base year, couple the audit to spatially explicit land-use and transport models for finer resolution, and test the indicator system through implementation in master and regulatory detailed plans, thereby validating whether the audited scenarios translate into measured reductions on the ground.</p>
<p><em>Source material: Special Research Report on Carbon Emissions Auditing for the Jiangsu Provincial Urban-System Plan (2011). All figures were reconstructed in English by the author from the report’s underlying data; all tables were converted to the values reported in the original study.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>