<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>research_brief – Shuai Ma</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-bba5ebae505b5c03f3f0d8040a416a6b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4PQ33SR2WK"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-4PQ33SR2WK', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shuai Ma</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../practice.html"> 
<span class="menu-text">Practice</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="living-safely-with-water-sponge-city-design-for-the-urban-waterfront" class="level1">
<h1>Living Safely with Water: Sponge-City Design for the Urban Waterfront</h1>
<section id="a-cross-case-framework-matching-lid-configurations-to-waterfront-site-types" class="level2">
<h2 class="anchored" data-anchor-id="a-cross-case-framework-matching-lid-configurations-to-waterfront-site-types">A cross-case framework matching LID configurations to waterfront site types</h2>
<p><strong>Shuai Ma</strong><br>
<strong>Role:</strong> Research Leader<br>
<strong>Type:</strong> Internal Research Report <strong>Date:</strong> 2017</p>
</section>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Waterfront development reshapes the very water system that makes a site attractive: it raises runoff and peak flow, interrupts drainage, and pushes polluted water into rivers and lakes faster. Sponge-city (low-impact development) practice is typically applied as a uniform checklist; this brief argues instead that the workable configuration is conditioned by site type. Drawing on six water-environment and sponge-city projects I worked on between 2011 and 2017, spanning watershed planning to a single CBD plot, it treats them as comparative cases read along three axes: site typology, where the treatment train places its emphasis (source control → conveyance and treatment → storage and reuse → controlled overflow), and measured performance. The methods range from SWMM hydraulic simulation to rational-method calculation, multi-criteria storage trade-offs, and watershed strategy. Five propositions emerge from the comparison: terrain governs source-zone design; low permeability and high groundwater rule out infiltration; density makes storage a residual and cost the binding constraint, so the largest harvesting system is rarely optimal; industrial sites need clean/dirty source separation before treatment; and at basin scale, plot-level LID must be paired with hydromorphological restoration. One rule holds throughout: an amenity water body reduces risk only when its storage, freeboard, water quality, and connectivity are quantified. Because the models were design tools rather than monitored systems, what I offer is a site-conditioned design framework, not claims about verified in-service performance.</p>
<p><strong>Research question.</strong> Under what site conditions, and through which configurations, can sponge-city (low-impact development) systems reduce a waterfront’s flood, drainage, and pollution risk <em>and</em> create ecological value at the same time?</p>
<p>Sponge-city practice is often applied as a uniform checklist of measures. Drawing on six water-environment and sponge-city projects I worked on between 2011 and 2017 - spanning watershed planning down to a single CBD plot - I treat the projects as comparative cases and ask what <em>changes</em> from site to site: which part of the treatment train should lead, and which performance objective binds, under each type of waterfront. The result is a set of <em>conditional</em> design propositions rather than a generic best-practice list.</p>
<p>Three sub-questions organize the comparison:</p>
<ul>
<li><em>Diagnostic</em> - how does waterfront urbanization change runoff volume, peak flow, and pollutant load across site types? (Kunshan, Houhai)</li>
<li><em>Evaluative</em> - how well does a sponge treatment train reduce those risks under design storms, and where does residual risk remain? (Gengwan)</li>
<li><em>Comparative</em> - how do site conditions decide the trade-off between flood control, water quality, reuse, ecology, and cost? (Suhewan, Mawan, Jinjiang)</li>
</ul>
</section>
<section id="analytical-framework" class="level2">
<h2 class="anchored" data-anchor-id="analytical-framework">Analytical framework</h2>
<p>I read each project along three axes:</p>
<ol type="1">
<li><strong>Site typology</strong> - scale, terrain, soil and groundwater, land use, dominant pollution source, and sensitivity of the receiving water.</li>
<li><strong>Configuration</strong> - where a project places the emphasis of the treatment train: <em>source control → conveyance and treatment → storage and reuse → controlled overflow</em>.</li>
<li><strong>Performance</strong> - runoff-volume and peak control, water quality, residual flooding, reuse yield, ecological value, and cost.</li>
</ol>
<p>The method is the same loop in every case - diagnose the hazard, set measurable targets, build a treatment train, then test residual risk and refine - but the projects differ in how far they could run that loop, from a full hydraulic model to a single-plot volume calculation.</p>
<p>The measures were compared on standard performance terms:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Sponge measure</th>
<th>Runoff-volume control</th>
<th>Peak-flow control</th>
<th>Reported SS removal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Permeable paving</td>
<td>Medium–strong</td>
<td>Medium</td>
<td>80–90%</td>
</tr>
<tr class="even">
<td>Green roof</td>
<td>Strong</td>
<td>Medium</td>
<td>70–80%</td>
</tr>
<tr class="odd">
<td>Rainwater wetland</td>
<td>Strong</td>
<td>Strong</td>
<td>50–80%</td>
</tr>
<tr class="even">
<td>Vegetated swale</td>
<td>Strong</td>
<td>Strong</td>
<td>35–90%</td>
</tr>
</tbody>
</table>
</section>
<section id="methodology-and-cases" class="level2">
<h2 class="anchored" data-anchor-id="methodology-and-cases">Methodology and cases</h2>
<p>This is a retrospective comparative multi-case study. The six cases were selected to span a <em>scale ladder</em> (watershed → district → plot) and contrasting site conditions, so that differences in configuration can be read against differences in site type rather than scale alone. The methods are matched to what each project needed: SWMM hydraulic simulation at Gengwan; rational-method and volume-budget calculation at Kunshan and Houhai; multi-criteria storage trade-off at Suhewan; pollution-risk-based spatial allocation at Mawan; and a staged watershed strategy at Jinjiang.</p>
<p><strong>On the strength of the evidence.</strong> These were professional design projects. The models were decision tools, generally <em>not</em> calibrated against gauged data or validated by post-construction monitoring, and the standards cited were those current at the time. The findings below are therefore design propositions grounded in modeled and calculated evidence, not claims about verified in-service performance. I treat that limit as part of the method: the same framework would be sharpened by monitoring data, which is one of the directions I want to pursue.</p>
</section>
<section id="cross-case-comparison" class="level2">
<h2 class="anchored" data-anchor-id="cross-case-comparison">Cross-case comparison</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Project</th>
<th>Scale</th>
<th>Waterfront type &amp; binding constraint</th>
<th>Dominant configuration</th>
<th>Leading objective</th>
<th>Key evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Jinjiang</strong></td>
<td>Watershed / river network</td>
<td>Citywide river system; diffuse and point pollution, single water source, over-hardened channels</td>
<td>Staged basin strategy: point-source → non-point → restore self-purification; softened banks, buffers, re-meandering</td>
<td>Receiving-water recovery</td>
<td>Runoff coeff. target 0.85 → 0.55; 30 m riparian buffer; design velocity 0.012–0.046 m/s</td>
</tr>
<tr class="even">
<td><strong>Gengwan</strong></td>
<td>District / new town</td>
<td>Steep mountain catchments draining to engineered amenity lakes; polluted first flush to sensitive water</td>
<td>Source dispersal (gullies, dry creek) → graded swales by road type → lakeside filter trench → lakes as controlled storage; SWMM-tested</td>
<td>Flood and quality, with modeled residual risk</td>
<td>100 m swale/ha → outlet TSS &lt; 10 mg/L; refined 50-yr storm: 6,551 m³ to lake, +0.12 m, no site flooding</td>
</tr>
<tr class="odd">
<td><strong>Mawan</strong></td>
<td>District / industrial</td>
<td>Waste-to-energy plant; vegetated slope and refuse-truck production roads; mixed pollution; limited green area</td>
<td>Clean/dirty source separation; distributed LID and a 2–3-stage rainwater wetland for clean runoff; dirty roads to controlled collection</td>
<td>Pollution control and ecological demonstration</td>
<td>Full reuse target not feasible → sponge used for pollution control and habitat/education</td>
</tr>
<tr class="even">
<td><strong>Kunshan</strong></td>
<td>District → plot / residential</td>
<td>Flat former farmland; low soil permeability, high groundwater</td>
<td>Shift from infiltration to detention: bioretention + underdrain + overflow + permeable surfaces; pond as detention</td>
<td>Restore pre-development water balance</td>
<td>Runoff coeff. 0.25 → 0.553; +2,171.5 m³ and peak 709 → 1,568 L/s (2-yr storm)</td>
</tr>
<tr class="odd">
<td><strong>Houhai</strong></td>
<td>District / dense infill</td>
<td>Dense urban infill; clay and loam soils; space-limited; policy-target-driven</td>
<td>Land-cover conversion (permeable paving, green roof, sunken green) + engineered storage to close the gap</td>
<td>Meet annual runoff-control target</td>
<td>60% (clay) / 70% (loam) control; 40% non-point reduction; 5-yr drainage storm; +340 m³ tank</td>
</tr>
<tr class="even">
<td><strong>Suhewan</strong></td>
<td>Plot / CBD</td>
<td>Ultra-dense CBD; 216 m tower over underground space; reuse economics</td>
<td>Roof-focused harvesting + right-sized storage; oversized max-collection option rejected</td>
<td>Storage economics and water quality</td>
<td>Max-collection 1,077 m³ rejected → 350 m³ (Parcel 46), 370 m³ (Parcel 44)</td>
</tr>
</tbody>
</table>
</section>
<section id="conditional-findings" class="level2">
<h2 class="anchored" data-anchor-id="conditional-findings">Conditional findings</h2>
<p>The configuration that works is conditioned by the site:</p>
<ol type="1">
<li><strong>Terrain leads at the source.</strong> On steep mountain-to-water sites, the binding risk is upland energy and a polluted first flush reaching sensitive receiving water, so the train must lead with source-zone dispersal and use amenity water bodies as terminal controlled storage - sized by simulation, not by an infiltration assumption. <em>(Gengwan)</em></li>
<li><strong>Soil and groundwater can void infiltration.</strong> On flat, low-permeability, high-groundwater greenfield sites, infiltration cannot be assumed; the train shifts to detention with underdrained bioretention and overflow, and the goal becomes restoring the pre-development volume and peak rather than draining water away faster. <em>(Kunshan)</em></li>
<li><strong>Density makes storage the residual, and cost the constraint.</strong> On dense infill and CBD plots, surface LID is space-limited: land-cover conversion gets partway and engineered storage closes the gap, at which point the binding question is storage cost and water quality. The largest harvesting system is not the optimum - Suhewan’s 1,077 m³ maximum was rejected for a 350 m³ design. <em>(Houhai, Suhewan)</em></li>
<li><strong>Pollution sources demand separation before treatment.</strong> On industrial or mixed waterfronts, the decisive move is separating clean from dirty runoff, not applying uniform LID; once the dirty routes are isolated, the landscape train is free to double as habitat and public education. <em>(Mawan)</em></li>
<li><strong>Plot-level LID is necessary but not sufficient at basin scale.</strong> At watershed scale, site measures must be paired with staged pollutant control and hydromorphological change - softened banks, buffers, re-meandering - to restore the receiving water’s own self-purification. <em>(Jinjiang)</em></li>
</ol>
<p>Across all six, one rule holds: an amenity water body lowers risk only when its storage, freeboard, water quality, and drainage connectivity are quantified.</p>
</section>
<section id="case-evidence" class="level2">
<h2 class="anchored" data-anchor-id="case-evidence">Case evidence</h2>
<section id="gengwan-mountain-to-lake-new-district-the-fully-modeled-case" class="level3">
<h3 class="anchored" data-anchor-id="gengwan-mountain-to-lake-new-district-the-fully-modeled-case">Gengwan — mountain-to-lake new district (the fully modeled case)</h3>
<p>Local drainage was designed for only a 1–3-year storm while steep catchments, hardscape, and engineered lakes created several failure paths at once. I mapped the gullies, subcatchments, channels, lakes, and outlets, kept the floodway separate from the amenity-water system, and converted the map into a SWMM network to locate where flooding occurred and which links needed enlarging.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/gengwan-ecological-drainage-network-original.png" class="img-fluid figure-img"></p>
<figcaption>Original Gengwan ecological drainage network diagram</figcaption>
</figure>
</div>
<p><em>Figure 1. Drainage network, flow directions, lake system, and outlets, extracted from the original project deck.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/swmm-gengwan-model.jpg" class="img-fluid figure-img"></p>
<figcaption>Original SWMM model of Gengwan</figcaption>
</figure>
</div>
<p><em>Figure 2. Original SWMM study-area model: terrain, subcatchments, nodes, and outlets.</em></p>
<p>Simulation linked quantity and quality. Pollutants concentrated in the first ~20 minutes, larger storms diluted average TSS, and at about 100 m of swale per hectare the modeled outlet TSS fell below 10 mg/L. The landscape lake stayed a controlled store rather than a hazard:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Storm</th>
<th style="text-align: right;">Runoff to lake (m³)</th>
<th style="text-align: right;">Lake-level rise (m)</th>
<th style="text-align: right;">Modeled TSS (mg/L)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1-yr</td>
<td style="text-align: right;">1,969</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">13.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">3-yr</td>
<td style="text-align: right;">2,929</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">10.83</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50-yr</td>
<td style="text-align: right;">6,221</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">7.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">100-yr</td>
<td style="text-align: right;">6,922</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">7.62</td>
</tr>
</tbody>
</table>
<p>Node-level results still showed one low-lying subcatchment as the dominant ponding hotspot (a second 50-yr run reached ~1,053 m³ there with shorter swales), so the fix was spatial: more swale length and depressed detention at the flagged nodes. In the refined 50-yr scenario ~6,551 m³ entered the lake for a +0.12 m rise with no site flooding - the lake absorbed more water <em>by design</em> once the layout was tuned.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/gengwan-dry-creek-reference-original.jpg" class="img-fluid figure-img"></p>
<figcaption>Original dry-creek reference photograph</figcaption>
</figure>
</div>
<p><em>Figure 3. Stepped rock channel: it dissipates energy and turns conveyance into a landscape feature.</em></p>
</section>
<section id="mawan-industrial-waterfront-source-separation" class="level3">
<h3 class="anchored" data-anchor-id="mawan-industrial-waterfront-source-separation">Mawan — industrial waterfront (source separation)</h3>
<p>At the Mawan Energy Ecological Park, a waste-to-energy plant on the Shenzhen waterfront, the catchment mixed the vegetated Xiaonanshan slope, roofs, visitor areas, and refuse-truck production roads. Clean roof and pedestrian runoff entered a distributed LID system and a 2–3-stage rainwater wetland, while the production roads kept inlets on both sides so their dirtier runoff stayed under controlled collection. Limited green area meant the site could not meet Shenzhen’s full reuse standard, so the scheme used sponge methods for pollution control and a demonstration landscape rather than maximum harvesting.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/mawan-sponge-city-plan-original.jpg" class="img-fluid figure-img"></p>
<figcaption>Original Mawan sponge-city plan</figcaption>
</figure>
</div>
<p><em>Figure 4. Mawan site plan (original landscape report): blue corridors route runoff through green space and wetland around the buildings.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/mawan-rainwater-wetland-render-original.jpg" class="img-fluid figure-img"></p>
<figcaption>Original Mawan rainwater-wetland rendering</figcaption>
</figure>
</div>
<p><em>Figure 5. The wetland detains and filters runoff while doubling as habitat and a public route.</em></p>
</section>
<section id="kunshan-flat-high-groundwater-residential-infiltration-cannot-be-assumed" class="level3">
<h3 class="anchored" data-anchor-id="kunshan-flat-high-groundwater-residential-infiltration-cannot-be-assumed">Kunshan — flat, high-groundwater residential (infiltration cannot be assumed)</h3>
<p>On flat former farmland near Shanghai, development raised the runoff coefficient from 0.25 to 0.553; for a 2-year storm (86.8 mm) the calculated runoff rose by 2,171.5 m³ and peak flow from 709 to 1,568 L/s. Because soil permeability was low and groundwater high, a green facility was not automatically infiltrative, so the design combined bioretention, underdrainage, overflow, and permeable surfaces rather than relying on soakage.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/kunshan-bioretention-section-original.jpg" class="img-fluid figure-img"></p>
<figcaption>Original bioretention-section illustration</figcaption>
</figure>
</div>
<p><em>Figure 6. Bioretention section (Kunshan stormwater report): the planted depression stores, filters, and infiltrates beside the developed surface.</em></p>
</section>
<section id="houhai-and-suhewan-dense-infill-and-cbd-plot-storage-as-residual-economics-as-constraint" class="level3">
<h3 class="anchored" data-anchor-id="houhai-and-suhewan-dense-infill-and-cbd-plot-storage-as-residual-economics-as-constraint">Houhai and Suhewan — dense infill and CBD plot (storage as residual, economics as constraint)</h3>
<p>At Shenzhen Houhai a policy target became a site water budget: 60% annual control on clay (70% on loam), 40% non-point-source reduction, and a 5-year drainage storm. Land-cover conversion supplied part of the control and a ~340 m³ tank closed the remaining gap. At Shanghai Suhewan, a 216 m tower over dense underground space, the question was how large a reuse system to build. Collecting all hardscape and roof runoff implied a 1,077 m³ tank; weighed against demand, water quality, and cost, a roof-focused design of 350 m³ (Parcel 46) and 370 m³ (Parcel 44) was recommended instead.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Suhewan storage basis</th>
<th style="text-align: right;">Volume (m³)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sponge runoff-control requirement (Parcel 46)</td>
<td style="text-align: right;">343.24</td>
</tr>
<tr class="even">
<td>LEED collection of all hardscape + roof runoff</td>
<td style="text-align: right;">1,077.30</td>
</tr>
<tr class="odd">
<td>Three days’ demand, incl.&nbsp;toilet flushing</td>
<td style="text-align: right;">470.00</td>
</tr>
<tr class="even">
<td>Three days’ demand, excl. toilet flushing</td>
<td style="text-align: right;">340.00</td>
</tr>
<tr class="odd">
<td>Final roof-focused recommendation (Parcel 46)</td>
<td style="text-align: right;">350.00</td>
</tr>
<tr class="even">
<td>Final recommendation (Parcel 44)</td>
<td style="text-align: right;">370.00</td>
</tr>
</tbody>
</table>
</section>
<section id="jinjiang-watershed-plot-lid-is-not-enough" class="level3">
<h3 class="anchored" data-anchor-id="jinjiang-watershed-plot-lid-is-not-enough">Jinjiang — watershed (plot LID is not enough)</h3>
<p>At river-network scale the strategy was staged: near-term point-source treatment, mid-term diffuse-runoff control, and only then restoration of the river’s self-purification - straightened reaches re-meandered, banks and beds softened, and a 30 m planted buffer set back above the wet-season line, with channel velocities held to roughly 0.012–0.046 m/s. The parallel land target pulls the citywide runoff coefficient from about 0.85 toward 0.55. Landscape treatment alone cannot repair a river unless the pollutant load and the hydraulics change with it.</p>
</section>
</section>
<section id="implications-and-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="implications-and-next-steps">Implications and next steps</h2>
<p>Looking back across the six commissions, the clearest finding is that the configuration that reduces risk in one setting can fail in another. Testing these propositions against post-construction monitoring - and building a formal site-condition decision model that maps site attributes to treatment-train emphasis and storage strategy - is the work I want to pursue in doctoral study.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>