<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2021-09-01">

<title>Empirical Analysis of Guangzhou Residential Rental Markets – Shuai Ma</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-bba5ebae505b5c03f3f0d8040a416a6b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4PQ33SR2WK"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-4PQ33SR2WK', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Shuai Ma</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../practice.html"> 
<span class="menu-text">Practice</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#research-question-and-analytical-perspective" id="toc-research-question-and-analytical-perspective" class="nav-link" data-scroll-target="#research-question-and-analytical-perspective">1. Research question and analytical perspective</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">2. Data</a>
  <ul class="collapse">
  <li><a href="#source-and-scope" id="toc-source-and-scope" class="nav-link" data-scroll-target="#source-and-scope">2.1 Source and scope</a></li>
  <li><a href="#measurement-limitations" id="toc-measurement-limitations" class="nav-link" data-scroll-target="#measurement-limitations">2.2 Measurement limitations</a></li>
  </ul></li>
  <li><a href="#empirical-strategy" id="toc-empirical-strategy" class="nav-link" data-scroll-target="#empirical-strategy">3. Empirical strategy</a>
  <ul class="collapse">
  <li><a href="#hedonic-specification" id="toc-hedonic-specification" class="nav-link" data-scroll-target="#hedonic-specification">3.1 Hedonic specification</a></li>
  <li><a href="#preferred-specification" id="toc-preferred-specification" class="nav-link" data-scroll-target="#preferred-specification">3.2 Preferred specification</a></li>
  <li><a href="#model-selection-and-multicollinearity" id="toc-model-selection-and-multicollinearity" class="nav-link" data-scroll-target="#model-selection-and-multicollinearity">3.3 Model selection and multicollinearity</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">4. Results</a>
  <ul class="collapse">
  <li><a href="#model-fit-and-functional-form" id="toc-model-fit-and-functional-form" class="nav-link" data-scroll-target="#model-fit-and-functional-form">4.1 Model fit and functional form</a></li>
  <li><a href="#dwelling-attributes" id="toc-dwelling-attributes" class="nav-link" data-scroll-target="#dwelling-attributes">4.2 Dwelling attributes</a></li>
  <li><a href="#district-differentials" id="toc-district-differentials" class="nav-link" data-scroll-target="#district-differentials">4.3 District differentials</a></li>
  <li><a href="#diagnostics-and-robustness" id="toc-diagnostics-and-robustness" class="nav-link" data-scroll-target="#diagnostics-and-robustness">4.4 Diagnostics and robustness</a></li>
  </ul></li>
  <li><a href="#urban-market-interpretation" id="toc-urban-market-interpretation" class="nav-link" data-scroll-target="#urban-market-interpretation">5. Urban-market interpretation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">6. Conclusion</a></li>
  <li><a href="#appendix-a.-exploratory-market-segmentation" id="toc-appendix-a.-exploratory-market-segmentation" class="nav-link" data-scroll-target="#appendix-a.-exploratory-market-segmentation">Appendix A. Exploratory market segmentation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Empirical Analysis of Guangzhou Residential Rental Markets</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2021</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p style="font-size:0.9rem; color:var(--muted); margin-top:-0.5rem; margin-bottom:2rem;">
Shuai Ma &nbsp;·&nbsp; September 2021 &nbsp;·&nbsp; <a href="https://github.com/shuaima-research/PA-16-Guangzhou_Residential_Rental_Market-Github" target="_blank">Code (GitHub)</a>
</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This report studies the correlates of monthly asking rents in Guangzhou using 3,000 publicly available online rental listings collected and cleaned by the author for a September 2021 project. A hedonic regression framework relates rent to floor area, dwelling configuration, floor level, rental form, and district. The benchmark levels model explains approximately 59% of the cross-sectional variation in asking rents. Because rents are strongly right-skewed and the levels model is heteroskedastic, the preferred specification models log rent and reports heteroskedasticity-robust standard errors. Its results indicate that floor area is the dominant structural correlate: a 10% increase in area is associated with approximately 7.15% higher rent, holding observed attributes constant. Bathrooms and the building floor are also positively associated with rent, while an additional bedroom at a fixed floor area is associated with a small discount, consistent with more intensive subdivision of the same space. Location remains important after controlling for dwelling characteristics. Relative to Baiyun, the preferred model estimates conditional rent premiums of approximately 51% in Tianhe, 42% in Yuexiu, and 27% in Haizhu. These estimates describe market capitalization patterns; they should not be read as causal effects because the listings omit exact location, accessibility, building age, furnishing, and other quality dimensions.</p>
</section>
<section id="research-question-and-analytical-perspective" class="level2">
<h2 class="anchored" data-anchor-id="research-question-and-analytical-perspective">1. Research question and analytical perspective</h2>
<p>Housing is a bundle of attributes rather than a homogeneous commodity. Tenants jointly purchase interior space, room configuration, building position, neighborhood access, and a location within the metropolitan labor and amenity system. The hedonic framework developed by Lancaster (1966) and Rosen (1974) provides a natural empirical language for this market: observed rent is modeled as the price of a bundle of housing and location characteristics.</p>
<p>The central question is:</p>
<blockquote class="blockquote">
<p>Which observed dwelling and district characteristics are most strongly associated with residential asking rents in Guangzhou?</p>
</blockquote>
<p>The word <em>associated</em> is important. The data are a cross-section of online listings, not a randomized intervention or a panel of repeated transactions. The regressions identify conditional price differences within this sample. They do not isolate causal effects of district boundaries, floor area, or housing design.</p>
<p>The original project compared backward, forward, and bidirectional stepwise regression. Those procedures remain useful as sensitivity checks, but entry order is not an economic ranking of importance: it depends on units of measurement, correlations among regressors, and the chosen significance threshold. The main interpretation below therefore comes from a theory-led specification, joint tests, effect sizes, and robust uncertainty estimates.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">2. Data</h2>
<section id="source-and-scope" class="level3">
<h3 class="anchored" data-anchor-id="source-and-scope">2.1 Source and scope</h3>
<p>The analytical file contains 3,000 publicly accessible Guangzhou rental listings gathered from the internet and subsequently cleaned by the author. The observations represent advertised monthly rents rather than executed lease prices. Each row records the rental form, district, floor area, numbers of bedrooms, living rooms and bathrooms, building floor, a categorical floor-position indicator, a brand indicator, and monthly rent.</p>
<p>The sample is broad but not spatially balanced. Tianhe alone contributes 731 listings, whereas Conghua contributes only one. The Conghua observation is retained in descriptive totals but excluded from the preferred regressions because a district effect cannot be credibly estimated from a singleton. The preferred regression sample therefore contains 2,999 observations.</p>
<div class="cell">
<div id="tbl-descriptive" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Descriptive statistics for the analytical sample
</figcaption>
<div aria-describedby="tbl-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">P25</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">P75</th>
<th style="text-align: right;">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monthly rent</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">4428.79</td>
<td style="text-align: right;">4293.80</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">2300.0</td>
<td style="text-align: right;">3500.0</td>
<td style="text-align: right;">5000.0</td>
<td style="text-align: right;">95000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Floor area</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">70.96</td>
<td style="text-align: right;">46.08</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: right;">68.5</td>
<td style="text-align: right;">94.0</td>
<td style="text-align: right;">620</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bedrooms</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">2.46</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Living rooms</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bathrooms</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Building floor</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">18.27</td>
<td style="text-align: right;">10.57</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">17.0</td>
<td style="text-align: right;">28.0</td>
<td style="text-align: right;">60</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The rent distribution is markedly asymmetric. Median monthly rent is 3,500, mean rent is 4,429, and the maximum reaches 95,000. Floor area is similarly dispersed, ranging from 5 to 620 square meters. The contrast between the mean and median, together with the long upper tail in <a href="#fig-rent-distribution" class="quarto-xref">Figure&nbsp;1</a>, motivates a log-rent specification in addition to the original levels model.</p>
<div id="fig-rent-distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rent-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/rent_and_log_rent_distributions.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rent-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Raw rent and log-rent distributions.
</figcaption>
</figure>
</div>
<div class="cell">
<div id="tbl-district-sample" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-district-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: District coverage and unadjusted asking rents
</figcaption>
<div aria-describedby="tbl-district-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">District</th>
<th style="text-align: right;">Listings</th>
<th style="text-align: right;">Mean rent</th>
<th style="text-align: right;">Median rent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tianhe</td>
<td style="text-align: right;">731</td>
<td style="text-align: right;">6329</td>
<td style="text-align: right;">5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baiyun</td>
<td style="text-align: right;">485</td>
<td style="text-align: right;">3811</td>
<td style="text-align: right;">3000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Haizhu</td>
<td style="text-align: right;">477</td>
<td style="text-align: right;">4302</td>
<td style="text-align: right;">3600</td>
</tr>
<tr class="even">
<td style="text-align: left;">Panyu</td>
<td style="text-align: right;">415</td>
<td style="text-align: right;">3373</td>
<td style="text-align: right;">3000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liwan</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">3619</td>
<td style="text-align: right;">2800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuexiu</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">4790</td>
<td style="text-align: right;">4000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huangpu</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">3556</td>
<td style="text-align: right;">3800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zengcheng</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">2535</td>
<td style="text-align: right;">2400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nansha</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">3398</td>
<td style="text-align: right;">2500</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huadu</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">2126</td>
<td style="text-align: right;">2100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conghua</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4000</td>
<td style="text-align: right;">4000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>These raw district averages mix location with dwelling composition. Tianhe’s mean rent, for example, may be higher because its listings are larger or differ in rental form. Regression is used to separate those observed compositional differences from the remaining district differential.</p>
</section>
<section id="measurement-limitations" class="level3">
<h3 class="anchored" data-anchor-id="measurement-limitations">2.2 Measurement limitations</h3>
<p>Five limitations shape the interpretation of every estimate:</p>
<ol type="1">
<li><strong>Asking price is not transaction price.</strong> Negotiation and unobserved vacancy duration may separate advertised rent from the final lease.</li>
<li><strong>Online coverage is selective.</strong> Platform listings may overrepresent professionally marketed, newer, or more central properties.</li>
<li><strong>Location is coarse.</strong> District indicators cannot capture metro proximity, employment access, school quality, neighborhood amenities, or within-district submarkets.</li>
<li><strong>Housing quality is incomplete.</strong> Building age, elevator access, furnishing, renovation quality, orientation, and property-management services are unavailable.</li>
<li><strong>Some indicators are nearly redundant.</strong> <code>Type</code> and <code>Brand</code> have a sample correlation of 0.985, so their separate coefficients in the full model are unstable.</li>
</ol>
<p>The results are consequently best read as a careful description of this online market sample, not as a complete structural model of Guangzhou’s rental market.</p>
</section>
</section>
<section id="empirical-strategy" class="level2">
<h2 class="anchored" data-anchor-id="empirical-strategy">3. Empirical strategy</h2>
<section id="hedonic-specification" class="level3">
<h3 class="anchored" data-anchor-id="hedonic-specification">3.1 Hedonic specification</h3>
<p>The benchmark levels model follows the original project:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>R</mi><mi>e</mi><mi>n</mi><msub><mi>t</mi><mi>i</mi></msub><mo>=</mo><mi>α</mi><mo>+</mo><msub><mi>β</mi><mn>1</mn></msub><mi>T</mi><mi>y</mi><mi>p</mi><msub><mi>e</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>2</mn></msub><mi>A</mi><mi>r</mi><mi>e</mi><msub><mi>a</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>3</mn></msub><msub><mi>B</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>4</mn></msub><msub><mi>L</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>5</mn></msub><msub><mi>R</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>6</mn></msub><mi>F</mi><mi>l</mi><mi>o</mi><mi>o</mi><msub><mi>r</mi><mi>i</mi></msub><mo>+</mo><msup><mi>𝛅</mi><mo>′</mo></msup><mi>D</mi><mi>i</mi><mi>s</mi><mi>t</mi><mi>r</mi><mi>i</mi><mi>c</mi><msub><mi>t</mi><mi>i</mi></msub><mo>+</mo><msup><mi>𝛉</mi><mo>′</mo></msup><mi>H</mi><msub><mi>F</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>7</mn></msub><mi>B</mi><mi>r</mi><mi>a</mi><mi>n</mi><msub><mi>d</mi><mi>i</mi></msub><mo>+</mo><msub><mi>ε</mi><mi>i</mi></msub><mi>.</mi></mrow><annotation encoding="application/x-tex">
Rent_i = \alpha + \beta_1 Type_i + \beta_2 Area_i + \beta_3 B_i
+ \beta_4 L_i + \beta_5 R_i + \beta_6 Floor_i
+ \boldsymbol{\delta}'District_i + \boldsymbol{\theta}'HF_i
+ \beta_7 Brand_i + \varepsilon_i .
</annotation></semantics></math></p>
<p>Here, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>B</mi><annotation encoding="application/x-tex">B</annotation></semantics></math>, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>L</mi><annotation encoding="application/x-tex">L</annotation></semantics></math>, and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>R</mi><annotation encoding="application/x-tex">R</annotation></semantics></math> denote bedrooms, living rooms, and bathrooms. <code>Floor</code> is the numerical building floor, while <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>H</mi><mi>F</mi></mrow><annotation encoding="application/x-tex">HF</annotation></semantics></math> distinguishes low, middle, and high floor categories. District fixed effects absorb average observed and unobserved differences shared by listings in the same district.</p>
<p>The presentation underlying this report described two versions of this benchmark that differ only in how the categorical regressors are coded. Model 1 enters location and floor position as single categorical variables (<code>District</code> and <code>HF</code>), letting the estimation routine construct the contrasts internally. Model 2 instead enters them as explicit indicator columns: one dummy per district (Baiyun, Tianhe, Haizhu, and so on through Zengcheng) together with separate high-, middle-, and low-floor dummies. Econometrically the two are the same specification once one district indicator and one floor indicator are dropped as reference categories. They yield identical coefficients on the retained terms, fitted values, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>R</mi><mn>2</mn></msup><annotation encoding="application/x-tex">R^2</annotation></semantics></math>, and residuals, so their agreement is an algebraic identity rather than independent confirmation. The levels-model residual histogram reported below (<a href="#fig-levels-residuals" class="quarto-xref">Figure&nbsp;2</a>, whose panel is titled “linear model 2”) is computed from Model 2 and therefore characterizes Model 1 equally well.</p>
</section>
<section id="preferred-specification" class="level3">
<h3 class="anchored" data-anchor-id="preferred-specification">3.2 Preferred specification</h3>
<p>Three decisions define the preferred model:</p>
<ul>
<li>Conghua is excluded because it has only one listing.</li>
<li>Baiyun is set explicitly as the district reference because it has a large sample and provides a useful middle-market comparison.</li>
<li><code>Brand</code> is omitted because it is almost perfectly correlated with rental form. Retaining both creates severe variance inflation without improving adjusted fit.</li>
</ul>
<p>The preferred equation uses log rent and log floor area:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mrow><mi mathvariant="normal">log</mi><mo>⁡</mo></mrow><mo stretchy="false" form="prefix">(</mo><mi>R</mi><mi>e</mi><mi>n</mi><msub><mi>t</mi><mi>i</mi></msub><mo stretchy="false" form="postfix">)</mo><mo>=</mo><mi>α</mi><mo>+</mo><msub><mi>β</mi><mn>1</mn></msub><mi>T</mi><mi>y</mi><mi>p</mi><msub><mi>e</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>2</mn></msub><mrow><mi mathvariant="normal">log</mi><mo>⁡</mo></mrow><mo stretchy="false" form="prefix">(</mo><mi>A</mi><mi>r</mi><mi>e</mi><msub><mi>a</mi><mi>i</mi></msub><mo stretchy="false" form="postfix">)</mo><mo>+</mo><msub><mi>β</mi><mn>3</mn></msub><msub><mi>B</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>4</mn></msub><msub><mi>L</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>5</mn></msub><msub><mi>R</mi><mi>i</mi></msub><mo>+</mo><msub><mi>β</mi><mn>6</mn></msub><mi>F</mi><mi>l</mi><mi>o</mi><mi>o</mi><msub><mi>r</mi><mi>i</mi></msub><mo>+</mo><msup><mi>𝛅</mi><mo>′</mo></msup><mi>D</mi><mi>i</mi><mi>s</mi><mi>t</mi><mi>r</mi><mi>i</mi><mi>c</mi><msub><mi>t</mi><mi>i</mi></msub><mo>+</mo><msup><mi>𝛉</mi><mo>′</mo></msup><mi>H</mi><msub><mi>F</mi><mi>i</mi></msub><mo>+</mo><msub><mi>ε</mi><mi>i</mi></msub><mi>.</mi></mrow><annotation encoding="application/x-tex">
\log(Rent_i) = \alpha + \beta_1 Type_i + \beta_2 \log(Area_i)
+ \beta_3 B_i + \beta_4 L_i + \beta_5 R_i + \beta_6 Floor_i
+ \boldsymbol{\delta}'District_i + \boldsymbol{\theta}'HF_i + \varepsilon_i .
</annotation></semantics></math></p>
<p>The log transformation reduces the leverage of a small number of very expensive listings and permits an elasticity interpretation for floor area. Because a Breusch–Pagan diagnostic still rejects homoskedasticity after transformation, all preferred-model tests and confidence intervals use HC1 heteroskedasticity-robust standard errors.</p>
</section>
<section id="model-selection-and-multicollinearity" class="level3">
<h3 class="anchored" data-anchor-id="model-selection-and-multicollinearity">3.3 Model selection and multicollinearity</h3>
<p>The original forward-selection path entered area first, followed by district and floor-related information; backward selection treated brand and categorical floor position as comparatively weak. This pattern is informative, but stepwise selection does not establish that the first variable entered has the largest causal or economic effect. It also behaves unpredictably when regressors overlap. In this sample, rental form and brand are nearly duplicates, while floor area is correlated with room counts. The negative bedroom coefficient discussed below is a conditional effect at fixed area, not evidence that larger dwellings rent for less.</p>
<p>Principal-component analysis confirms that structural attributes share common variation, especially area and room configuration. PCA is useful as a diagnostic but is not the main estimator because its synthetic components are harder to translate into planning or market terms.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">4. Results</h2>
<section id="model-fit-and-functional-form" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-and-functional-form">4.1 Model fit and functional form</h3>
<div class="cell">
<div id="tbl-model-fit" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Model fit
</figcaption>
<div aria-describedby="tbl-model-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 27%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">R-squared</th>
<th style="text-align: right;">Adjusted R-squared</th>
<th style="text-align: right;">Residual SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Benchmark levels model</td>
<td style="text-align: right;">3000</td>
<td style="text-align: right;">0.593</td>
<td style="text-align: right;">0.590</td>
<td style="text-align: right;">2747.725</td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferred levels model</td>
<td style="text-align: right;">2999</td>
<td style="text-align: right;">0.593</td>
<td style="text-align: right;">0.591</td>
<td style="text-align: right;">2747.980</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Preferred log model</td>
<td style="text-align: right;">2999</td>
<td style="text-align: right;">0.783</td>
<td style="text-align: right;">0.782</td>
<td style="text-align: right;">0.291</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The benchmark model explains 59.3% of variation in rent, with an adjusted <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>R</mi><mn>2</mn></msup><annotation encoding="application/x-tex">R^2</annotation></semantics></math> of 0.590. Removing the collinear brand indicator and the Conghua singleton leaves adjusted fit essentially unchanged. This is strong evidence that <code>Brand</code> contributes almost no independent explanatory information once rental form and the other attributes are present.</p>
<p>The preferred log model has an <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>R</mi><mn>2</mn></msup><annotation encoding="application/x-tex">R^2</annotation></semantics></math> of 0.783. Because the dependent-variable scale differs, that value is not directly comparable to the levels-model <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>R</mi><mn>2</mn></msup><annotation encoding="application/x-tex">R^2</annotation></semantics></math> as a formal model-selection test. It does, however, show that the multiplicative specification tracks proportional rent variation well. The levels-model residual histogram in <a href="#fig-levels-residuals" class="quarto-xref">Figure&nbsp;2</a> displays the influence of expensive upper-tail observations that motivates this transformation.</p>
<div id="fig-levels-residuals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-levels-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/rent_rg_2_residual_histogram.png" class="img-fluid figure-img" style="width:78.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-levels-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Residual distribution from the original levels specification.
</figcaption>
</figure>
</div>
</section>
<section id="dwelling-attributes" class="level3">
<h3 class="anchored" data-anchor-id="dwelling-attributes">4.2 Dwelling attributes</h3>
<div class="cell">
<div id="tbl-structural-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-structural-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Preferred log-rent estimates for dwelling attributes
</figcaption>
<div aria-describedby="tbl-structural-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 27%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Robust SE</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rental form (Type = 1)</td>
<td style="text-align: right;">-0.417</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">-34.1% relative to Type = 0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log floor area</td>
<td style="text-align: right;">0.715</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">Elasticity: 0.715</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bedrooms</td>
<td style="text-align: right;">-0.035</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: left;">-3.4% per additional bedroom</td>
</tr>
<tr class="even">
<td style="text-align: left;">Living rooms</td>
<td style="text-align: right;">-0.021</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: left;">-2.0% per additional living room</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bathrooms</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">+13.9% per additional bathroom</td>
</tr>
<tr class="even">
<td style="text-align: left;">Building floor</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">+1.1% per additional floor</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low-floor category</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: left;">+3.3% relative to middle floor</td>
</tr>
<tr class="even">
<td style="text-align: left;">High-floor category</td>
<td style="text-align: right;">-0.029</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: left;">-2.9% relative to middle floor</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Floor area is the most stable structural correlate. Its coefficient of 0.715 is an elasticity: a 10% larger dwelling is associated with approximately 7.15% higher rent, all else equal. The relationship is positive but less than proportional, implying a lower monthly rent per square meter for larger units within the observed range.</p>
<p>An additional bathroom is associated with approximately 13.9% higher rent. By contrast, an additional bedroom at the same total area is associated with about 3.4% lower rent. This does not mean that larger multi-bedroom dwellings are cheaper. Rather, among units of equal area, a higher bedroom count likely represents more partitioned space and smaller rooms. Living-room count has no statistically distinguishable independent association after area, bedrooms, and bathrooms are held constant (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>p</mi><mo>=</mo><mn>0.155</mn></mrow><annotation encoding="application/x-tex">p=0.155</annotation></semantics></math>).</p>
<p>Each additional building floor is associated with roughly 1.1% higher rent. The separate low/middle/high category effects are much smaller and sensitive to functional form. Their signs should not be overinterpreted because they coexist with the continuous floor measure. The continuous floor gradient is the clearer result.</p>
<p>The coefficient on rental form is negative after conditioning on area and room counts, even though Type 1 listings have much higher unadjusted rents and much larger average areas. This reversal reflects the unusual composition of the two groups and the near-duplication between <code>Type</code> and <code>Brand</code>. Rental form matters for prediction, but its coefficient should not be given a structural or causal interpretation without a verified codebook and a cleaner separation of rental form from platform brand.</p>
</section>
<section id="district-differentials" class="level3">
<h3 class="anchored" data-anchor-id="district-differentials">4.3 District differentials</h3>
<div id="fig-district-effects" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-district-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/adjusted_district_rent_differentials.png" class="img-fluid figure-img" style="width:88.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-district-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Adjusted district rent differentials relative to Baiyun.
</figcaption>
</figure>
</div>
<div class="cell">
<div id="tbl-district-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-district-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Adjusted district rent differentials relative to Baiyun
</figcaption>
<div aria-describedby="tbl-district-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">District</th>
<th style="text-align: right;">Difference (%)</th>
<th style="text-align: right;">95% robust CI</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Huadu</td>
<td style="text-align: right;">-47.6</td>
<td style="text-align: right;">[-50.5, -44.6]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zengcheng</td>
<td style="text-align: right;">-46.7</td>
<td style="text-align: right;">[-50.1, -43.0]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nansha</td>
<td style="text-align: right;">-34.4</td>
<td style="text-align: right;">[-39.9, -28.5]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Panyu</td>
<td style="text-align: right;">-8.6</td>
<td style="text-align: right;">[-12.3, -4.9]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huangpu</td>
<td style="text-align: right;">+3.0</td>
<td style="text-align: right;">[-1.7, +7.9]</td>
<td style="text-align: right;">0.215</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liwan</td>
<td style="text-align: right;">+6.9</td>
<td style="text-align: right;">[+1.7, +12.3]</td>
<td style="text-align: right;">0.008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Haizhu</td>
<td style="text-align: right;">+27.2</td>
<td style="text-align: right;">[+22.5, +32.1]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuexiu</td>
<td style="text-align: right;">+41.7</td>
<td style="text-align: right;">[+34.9, +48.8]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tianhe</td>
<td style="text-align: right;">+51.2</td>
<td style="text-align: right;">[+45.7, +57.0]</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>District indicators are jointly significant (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>F</mi><mo>=</mo><mn>59.05</mn></mrow><annotation encoding="application/x-tex">F=59.05</annotation></semantics></math>, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>p</mi><mo>&lt;</mo><mn>0.001</mn></mrow><annotation encoding="application/x-tex">p&lt;0.001</annotation></semantics></math>), confirming that broad location remains associated with rent after observed dwelling attributes are controlled. Relative to Baiyun, otherwise comparable listings are estimated to rent for approximately 51% more in Tianhe, 42% more in Yuexiu, and 27% more in Haizhu. Liwan has a smaller premium of about 7%. Huangpu is statistically indistinguishable from Baiyun.</p>
<p>Panyu has an estimated discount of 9%, while Nansha, Zengcheng, and Huadu show substantially lower conditional rents. This ordering is consistent with the capitalization of central-city employment access, transit connectivity, and established urban amenities. It does not prove that any one of those mechanisms causes the premium, because exact accessibility and neighborhood quality are not observed. Conghua is omitted from <a href="#tbl-district-effects" class="quarto-xref">Table&nbsp;5</a> because its single listing cannot support a district estimate.</p>
</section>
<section id="diagnostics-and-robustness" class="level3">
<h3 class="anchored" data-anchor-id="diagnostics-and-robustness">4.4 Diagnostics and robustness</h3>
<div class="cell">
<div id="tbl-diagnostics" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Selected model diagnostics
</figcaption>
<div aria-describedby="tbl-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Diagnostic</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Correlation between Type and Brand</td>
<td style="text-align: right;">0.985</td>
</tr>
<tr class="even">
<td style="text-align: left;">District fixed effects: partial F-statistic</td>
<td style="text-align: right;">59.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">District fixed effects: p-value</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Floor-category indicators: partial F-statistic</td>
<td style="text-align: right;">2.584</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Floor-category indicators: p-value</td>
<td style="text-align: right;">0.076</td>
</tr>
<tr class="even">
<td style="text-align: left;">Levels model: Breusch-Pagan statistic</td>
<td style="text-align: right;">87.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Levels model: Breusch-Pagan p-value</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log model: Breusch-Pagan statistic</td>
<td style="text-align: right;">17.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log model: Breusch-Pagan p-value</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The diagnostics support four conclusions. First, the district effects add substantial explanatory power as a group. Second, the levels model is clearly heteroskedastic. Logging rent reduces, but does not eliminate, that pattern; robust standard errors remain necessary. Third, the correlation of 0.985 between <code>Type</code> and <code>Brand</code> makes their separate full-model coefficients unreliable. Fourth, residual normality is not a useful gatekeeper for this large cross-section. A conventional one-sample Kolmogorov–Smirnov test is especially inappropriate when the comparison distribution’s mean and variance are estimated from the same residuals. The report therefore bases inference on robust standard errors rather than a claim of normally distributed residuals.</p>
<div id="fig-pca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/pca_parallel_analysis.png" class="img-fluid figure-img" style="width:78.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Parallel analysis for the principal-component diagnostic.
</figcaption>
</figure>
</div>
<p>The parallel analysis in <a href="#fig-pca" class="quarto-xref">Figure&nbsp;4</a> retains many components, which is not surprising: the input mixes dwelling attributes with mutually exclusive district indicators. The result reinforces the existence of several independent dimensions but does not offer a more interpretable substitute for the hedonic regression.</p>
</section>
</section>
<section id="urban-market-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="urban-market-interpretation">5. Urban-market interpretation</h2>
<p>Three market patterns stand out.</p>
<p>First, <strong>space is the principal rent-bearing housing attribute</strong>. The area elasticity is large and precisely estimated. The negative bedroom coefficient at fixed area also suggests that renters value usable spaciousness, not merely the number of partitions advertised in a floor plan.</p>
<p>Second, <strong>Guangzhou’s rental market displays a pronounced center-oriented spatial gradient</strong>. Tianhe, Yuexiu, and Haizhu retain sizable premiums after observed unit characteristics are held constant. These districts combine employment concentration, mature services, and extensive transport access. The estimates are consistent with those advantages being capitalized into asking rents.</p>
<p>Third, <strong>coarse district controls leave important geography unresolved</strong>. A district is too large to represent a single housing submarket. A listing near a metro station in outer Panyu may compete more directly with an inner-city listing than with a distant listing in the same district. The present district coefficients average across such variation.</p>
<p>For planning, the results point toward a familiar tension. Accessibility raises the attractiveness of centrally connected areas but can also be capitalized into higher housing costs. Expanding rental supply in job-rich and transit-accessible locations, while improving cross-district connectivity, may broaden access to those advantages. This inference is a planning interpretation, not an effect identified by the present regression.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">6. Conclusion</h2>
<p>The analysis finds that both dwelling size and metropolitan location organize Guangzhou’s online rental market. The original levels regression explains about 59% of asking-rent variation. A preferred log-rent specification provides a better-behaved representation of the strongly skewed market and shows that a 10% increase in floor area is associated with roughly 7.15% higher rent. Bathrooms and building floor are positively associated with rent, while room-count effects must be interpreted conditional on total area. Even after those controls, Tianhe, Yuexiu, and Haizhu command substantial premiums relative to Baiyun.</p>
<p>The strongest conclusion is not that one stepwise algorithm has discovered a definitive list of price determinants. It is that housing attributes and urban location jointly shape asking rents, while omitted quality, accessibility, selection into online platforms, and non-random spatial composition limit causal claims. A subsequent study should retain exact coordinates, distance to metro stations and employment centers, building age, furnishing, elevator access, listing date, and platform identifiers. Geocoded data would permit neighborhood fixed effects, spatial diagnostics, and repeated cross-sections; transaction or contract data would further separate asking behavior from realized market prices.</p>
</section>
<section id="appendix-a.-exploratory-market-segmentation" class="level2">
<h2 class="anchored" data-anchor-id="appendix-a.-exploratory-market-segmentation">Appendix A. Exploratory market segmentation</h2>
<p>The original project also used K-means and hierarchical clustering. The within-cluster sum-of-squares curve supports a four-cluster exploratory solution.</p>
<div id="fig-kmeans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/kmeans_wss.png" class="img-fluid figure-img" style="width:78.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Within-cluster sum of squares for K-means clustering.
</figcaption>
</figure>
</div>
<div class="cell">
<div id="tbl-cluster-profiles" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cluster-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Profiles of the four K-means clusters
</figcaption>
<div aria-describedby="tbl-cluster-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Cluster</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean rent</th>
<th style="text-align: right;">Median rent</th>
<th style="text-align: right;">Mean area</th>
<th style="text-align: right;">Mean bedrooms</th>
<th style="text-align: right;">Mean living rooms</th>
<th style="text-align: right;">Mean bathrooms</th>
<th style="text-align: right;">Mean floor</th>
<th style="text-align: right;">Share Type 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">385</td>
<td style="text-align: right;">1612.10</td>
<td style="text-align: right;">1590.00</td>
<td style="text-align: right;">10.68</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.52</td>
<td style="text-align: right;">20.21</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1508</td>
<td style="text-align: right;">3847.09</td>
<td style="text-align: right;">3450.00</td>
<td style="text-align: right;">62.19</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">16.11</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">849</td>
<td style="text-align: right;">6697.99</td>
<td style="text-align: right;">5000.00</td>
<td style="text-align: right;">115.94</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">22.39</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">258</td>
<td style="text-align: right;">4564.78</td>
<td style="text-align: right;">4000.00</td>
<td style="text-align: right;">64.14</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">14.42</td>
<td style="text-align: right;">1.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The clusters primarily separate a small-space, low-rent Type 0 segment; a broad middle segment; and larger, higher-rent units. This is descriptive rather than a formal test of submarket boundaries. K-means distance is sensitive to scaling and to the inclusion of binary district indicators, so the cluster labels should not replace the regression-based interpretation.</p>
<div id="fig-hierarchical" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hierarchical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/hierarchical_ward.png" class="img-fluid figure-img" style="width:82.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hierarchical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Ward hierarchical clustering dendrogram.
</figcaption>
</figure>
</div>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Breusch, T. S., and A. R. Pagan. 1979. “A Simple Test for Heteroscedasticity and Random Coefficient Variation.” <em>Econometrica</em> 47 (5): 1287–1294.</p>
<p>Lancaster, K. J. 1966. “A New Approach to Consumer Theory.” <em>Journal of Political Economy</em> 74 (2): 132–157.</p>
<p>Rosen, S. 1974. “Hedonic Prices and Implicit Markets: Product Differentiation in Pure Competition.” <em>Journal of Political Economy</em> 82 (1): 34–55.</p>
<p>White, H. 1980. “A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity.” <em>Econometrica</em> 48 (4): 817–838.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var el = document.getElementById('title-block-header');
    if (el) el.style.setProperty('display', 'block', 'important');
  });
</script>




</body></html>